export const SUPERADMIN_LIST_ADMIN = 'SUPERADMIN_LIST_ADMIN';
export const SUPERADMIN_ADD_ADMIN = 'SUPERADMIN_ADD_ADMIN';
export const SUPERADMIN_UPDATE_ADMIN = 'SUPERADMIN_UPDATE_ADMIN';
export const SUPERADMIN_DELETE_ADMIN = 'SUPERADMIN_DELETE_ADMIN';
export const SUPERADMIN_GET_ADMIN = 'SUPERADMIN_GET_ADMIN';
export const SUPERADMIN_RESET_ADMIN = 'SUPERADMIN_RESET_ADMIN';