export const SUPERADMIN_CART_LIST = 'SUPERADMIN_CART_LIST';
export const SUPERADMIN_CART_ADD = 'SUPERADMIN_CART_ADD';
export const SUPERADMIN_CART_DELETE = 'SUPERADMIN_CART_DELETE';
export const SUPERADMIN_CART_RESET = 'SUPERADMIN_CART_RESET';
export const SUPERADMIN_CART_RESET_LIST = 'SUPERADMIN_CART_RESET_LIST';