export const LIST_CERTIFICATE = 'LIST_CERTIFICATE';
export const ADD_CERTIFICATE = 'ADD_CERTIFICATE';
export const GET_CERTIFICATE = 'GET_CERTIFICATE';
export const UPDATE_CERTIFICATE = 'UPDATE_CERTIFICATE';
export const DELETE_CERTIFICATE = 'DELETE_CERTIFICATE';