export const LIST_COUNTRY = 'LIST_COUNTRY';
export const ADD_COUNTRY = 'ADD_COUNTRY';
export const UPDATE_COUNTRY = 'UPDATE_COUNTRY';
export const DELETE_COUNTRY = 'DELETE_COUNTRY';
export const GET_COUNTRY = 'GET_COUNTRY';