export const LIST_DISTRICT = 'LIST_DISTRICT';
export const ADD_DISTRICT = 'ADD_DISTRICT';
export const UPDATE_DISTRICT = 'UPDATE_DISTRICT';
export const DELETE_DISTRICT = 'DELETE_DISTRICT';
export const GET_DISTRICT = 'GET_DISTRICT';