export const SUPERADMIN_LIST_DISTRIBUTOR = 'SUPERADMIN_LIST_DISTRIBUTOR';
export const SUPERADMIN_ADD_DISTRIBUTOR = 'SUPERADMIN_ADD_DISTRIBUTOR';
export const SUPERADMIN_UPDATE_DISTRIBUTOR = 'SUPERADMIN_UPDATE_DISTRIBUTOR';
export const SUPERADMIN_DELETE_DISTRIBUTOR = 'SUPERADMIN_DELETE_DISTRIBUTOR';
export const SUPERADMIN_GET_DISTRIBUTOR = 'SUPERADMIN_GET_DISTRIBUTOR';
export const SUPERADMIN_RESET_DISTRIBUTOR = 'SUPERADMIN_RESET_DISTRIBUTOR';