export const SUPERADMIN_LIST_EMPLOYEE_SALARY = 'SUPERADMIN_LIST_EMPLOYEE_SALARY';
export const SUPERADMIN_ADD_EMPLOYEE_SALARY = 'SUPERADMIN_ADD_EMPLOYEE_SALARY';
export const SUPERADMIN_UPDATE_EMPLOYEE_SALARY = 'SUPERADMIN_UPDATE_EMPLOYEE_SALARY';
//export const SUPERADMIN_DELETE_EMPLOYEE_SALARY = 'SUPERADMIN_DELETE_EMPLOYEE_SALARY';
export const SUPERADMIN_GET_EMPLOYEE_SALARY = 'SUPERADMIN_GET_EMPLOYEE_SALARY';
export const SUPERADMIN_RESET_EMPLOYEE_SALARY = 'SUPERADMIN_RESET_EMPLOYEE_SALARY';