export const SUPERADMIN_LIST_EMPLOYEE = 'SUPERADMIN_LIST_EMPLOYEE';
export const SUPERADMIN_ADD_EMPLOYEE = 'SUPERADMIN_ADD_EMPLOYEE';
export const SUPERADMIN_UPDATE_EMPLOYEE = 'SUPERADMIN_UPDATE_EMPLOYEE';
export const SUPERADMIN_DELETE_EMPLOYEE = 'SUPERADMIN_DELETE_EMPLOYEE';
export const SUPERADMIN_GET_EMPLOYEE = 'SUPERADMIN_GET_EMPLOYEE';
export const SUPERADMIN_RESET_EMPLOYEE = 'SUPERADMIN_RESET_EMPLOYEE';