export const SUPERADMIN_LIST_EXPENSE = 'SUPERADMIN_LIST_EXPENSE';
export const SUPERADMIN_ADD_EXPENSE = 'SUPERADMIN_ADD_EXPENSE';
export const SUPERADMIN_UPDATE_EXPENSE = 'SUPERADMIN_UPDATE_EXPENSE';
//export const SUPERADMIN_DELETE_EXPENSE = 'SUPERADMIN_DELETE_EXPENSE';
export const SUPERADMIN_GET_EXPENSE = 'SUPERADMIN_GET_EXPENSE';
export const SUPERADMIN_RESET_EXPENSE = 'SUPERADMIN_RESET_EXPENSE';
export const SUPERADMIN_LIST_ATTENDANCE = 'SUPERADMIN_LIST_ATTENDANCE';
export const SUPERADMIN_UPDATE_ATTENDANCE = 'SUPERADMIN_UPDATE_ATTENDANCE';