export const LIST_FESTIVEOFFER = 'LIST_FESTIVEOFFER';
export const CREATE_FESTIVEOFFER = 'CREATE_FESTIVEOFFER';
export const ADD_FESTIVEOFFER = 'ADD_FESTIVEOFFER';
export const GET_FESTIVEOFFER = 'GET_FESTIVEOFFER';
export const UPDATE_FESTIVEOFFER = 'UPDATE_FESTIVEOFFER';
export const DELETE_FESTIVEOFFER = 'DELETE_FESTIVEOFFER';
export const RESET_FESTIVEOFFER = 'RESET_FESTIVEOFFER';
export const RESET_FESTIVEOFFER_LIST = 'RESET_FESTIVEOFFER_LIST';