export const LIST_HOMEPAGESETTING = 'LIST_HOMEPAGESETTING';
export const UPDATE_HOMEPAGESETTING = 'UPDATE_HOMEPAGESETTING';
export const RESET_HOMEPAGESETTING = 'RESET_HOMEPAGESETTING';
export const RESET_HOMEPAGESETTING_LIST = 'RESET_HOMEPAGESETTING_LIST';