export const SUPERADMIN_LIST_INVESTOR = 'SUPERADMIN_LIST_INVESTOR';
export const SUPERADMIN_ADD_INVESTOR = 'SUPERADMIN_ADD_INVESTOR';
export const SUPERADMIN_UPDATE_INVESTOR = 'SUPERADMIN_UPDATE_INVESTOR';
export const SUPERADMIN_DELETE_INVESTOR = 'SUPERADMIN_DELETE_INVESTOR';
export const SUPERADMIN_GET_INVESTOR = 'SUPERADMIN_GET_INVESTOR';
export const SUPERADMIN_RESET_INVESTOR = 'SUPERADMIN_RESET_INVESTOR';