export const LIST_MATERIAL_PRICE = 'LIST_MATERIAL_PRICE';
export const ADD_MATERIAL_PRICE = 'ADD_MATERIAL_PRICE';
export const UPDATE_MATERIAL_PRICE = 'UPDATE_MATERIAL_PRICE';
export const DELETE_MATERIAL_PRICE = 'DELETE_MATERIAL_PRICE';
export const GET_MATERIAL_PRICE = 'GET_MATERIAL_PRICE';
export const RESET_MATERIAL_PRICE = 'RESET_MATERIAL_PRICE';
export const MATERIAL_PRICE_PRODUCT_PRICE_INFO = 'MATERIAL_PRICE_PRODUCT_PRICE_INFO';