export const LIST_MATERIAL = 'LIST_MATERIAL';
export const ADD_MATERIAL = 'ADD_MATERIAL';
export const UPDATE_MATERIAL = 'UPDATE_MATERIAL';
export const DELETE_MATERIAL = 'DELETE_MATERIAL';
export const RESET_MATERIAL = 'RESET_MATERIAL';
export const SET_MATERIAL = 'SET_MATERIAL';
export const RESET_MATERIAL_LIST = 'RESET_MATERIAL_LIST';