export const LIST_NEW_ARRIVAL = 'LIST_NEW_ARRIVAL';
export const ADD_NEW_ARRIVAL = 'ADD_NEW_ARRIVAL';
export const GET_NEW_ARRIVAL = 'GET_NEW_ARRIVAL';
export const UPDATE_NEW_ARRIVAL = 'UPDATE_NEW_ARRIVAL';
export const DELETE_NEW_ARRIVAL = 'DELETE_NEW_ARRIVAL';
export const RESET_NEW_ARRIVAL = 'RESET_NEW_ARRIVAL';