export const SUPERADMIN_NOTIFICATION_LIST = 'SUPERADMIN_NOTIFICATION_LIST';
export const SUPERADMIN_NOTIFICATION_ADD = 'SUPERADMIN_NOTIFICATION_ADD';
export const SUPERADMIN_NOTIFICATION_READ = 'SUPERADMIN_NOTIFICATION_READ';