export const SUPERADMIN_LIST_ORDERS = 'SUPERADMIN_LIST_ORDERS';
export const SUPERADMIN_GET_ORDERS = 'SUPERADMIN_GET_ORDERS';
export const SUPERADMIN_CANCEL_ORDER = 'SUPERADMIN_CANCEL_ORDER';
export const SUPERADMIN_RESET_ORDERS = 'SUPERADMIN_RESET_ORDERS';