export const SUPERADMIN_LIST_PAYMENT = 'SUPERADMIN_LIST_PAYMENT';
export const SUPERADMIN_ADD_PAYMENT = 'SUPERADMIN_ADD_PAYMENT';
export const SUPERADMIN_RESET_PAYMENT = 'SUPERADMIN_RESET_PAYMENT';
export const SUPERADMIN_DUE_PAYMENT = 'SUPERADMIN_DUE_PAYMENT';
export const SUPERADMIN_RESET_ALL_PAYMENT = 'SUPERADMIN_RESET_ALL_PAYMENT';
export const SUPERADMIN_LIST_WALLET = 'SUPERADMIN_LIST_WALLET';