export const SUPERADMIN_UPDATE_PROFILE = 'SUPERADMIN_UPDATE_PROFILE';
export const SUPERADMIN_PROFILE_RESET = 'SUPERADMIN_PROFILE_RESET';
export const SUPERADMIN_CHANGE_PASSWORD_RESET = 'SUPERADMIN_CHANGE_PASSWORD_RESET';
export const SUPERADMIN_UPDATE_PASSWORD = 'SUPERADMIN_UPDATE_PASSWORD';
export const SUPERADMIN_DASHBOARD = 'SUPERADMIN_DASHBOARD';