export const LIST_PROMOCODE = 'LIST_PROMOCODE';
export const CREATE_PROMOCODE = 'CREATE_PROMOCODE';
export const ADD_PROMOCODE = 'ADD_PROMOCODE';
export const GET_PROMOCODE = 'GET_PROMOCODE';
export const UPDATE_PROMOCODE = 'UPDATE_PROMOCODE';
export const DELETE_PROMOCODE = 'DELETE_PROMOCODE';
export const RESET_PROMOCODE = 'RESET_PROMOCODE';
export const RESET_PROMOCODE_LIST = 'RESET_PROMOCODE_LIST';