export const SUPERADMIN_LIST_RETAILER = 'SUPERADMIN_LIST_RETAILER';
export const SUPERADMIN_ADD_RETAILER = 'SUPERADMIN_ADD_RETAILER';
export const SUPERADMIN_UPDATE_RETAILER = 'SUPERADMIN_UPDATE_RETAILER';
export const SUPERADMIN_DELETE_RETAILER = 'SUPERADMIN_DELETE_RETAILER';
export const SUPERADMIN_GET_RETAILER = 'SUPERADMIN_GET_RETAILER';
export const SUPERADMIN_RESET_RETAILER = 'SUPERADMIN_RESET_RETAILER';
export const SUPERADMIN_LIST_RETAILER_REVIEW = 'SUPERADMIN_LIST_RETAILER_REVIEW';