export const LIST_RETURN_POLICY = 'LIST_RETURN_POLICY';
export const ADD_RETURN_POLICY = 'ADD_RETURN_POLICY';
export const UPDATE_RETURN_POLICY = 'UPDATE_RETURN_POLICY';
export const DELETE_RETURN_POLICY = 'DELETE_RETURN_POLICY';
export const RESET_RETURN_POLICY = 'RESET_RETURN_POLICY';