export const SUPERADMIN_LIST_RETURN_ORDERS = 'SUPERADMIN_LIST_RETURN_ORDERS';
export const SUPERADMIN_GET_RETURN_ORDERS = 'SUPERADMIN_GET_RETURN_ORDERS';
export const SUPERADMIN_RESET_RETURN_ORDERS = 'SUPERADMIN_RESET_RETURN_ORDERS';