export const SUPERADMIN_LIST_ROLE = 'SUPERADMIN_LIST_ROLE';
export const SUPERADMIN_ADD_ROLE = 'SUPERADMIN_ADD_ROLE';
export const SUPERADMIN_GET_ROLE = 'SUPERADMIN_GET_ROLE';
export const SUPERADMIN_UPDATE_ROLE = 'SUPERADMIN_UPDATE_ROLE';
export const SUPERADMIN_DELETE_ROLE = 'SUPERADMIN_DELETE_ROLE';
export const SUPERADMIN_RESET_ROLE = 'SUPERADMIN_RESET_ROLE';