export const SUPERADMIN_LIST_SALESEXECUTIVE = 'SUPERADMIN_LIST_SALESEXECUTIVE';
export const SUPERADMIN_ADD_SALESEXECUTIVE = 'SUPERADMIN_ADD_SALESEXECUTIVE';
export const SUPERADMIN_UPDATE_SALESEXECUTIVE = 'SUPERADMIN_UPDATE_SALESEXECUTIVE';
export const SUPERADMIN_DELETE_SALESEXECUTIVE = 'SUPERADMIN_DELETE_SALESEXECUTIVE';
export const SUPERADMIN_GET_SALESEXECUTIVE = 'SUPERADMIN_GET_SALESEXECUTIVE';
export const SUPERADMIN_RESET_SALESEXECUTIVE = 'SUPERADMIN_RESET_SALESEXECUTIVE';