export const LIST_STOCKAPPLICATION = 'LIST_STOCKAPPLICATION';
export const ADD_STOCKAPPLICATION = 'ADD_STOCKAPPLICATION';
export const GET_STOCK_PRODUCT_LIST = 'GET_STOCK_PRODUCT_LIST';
export const GET_STOCK_PRODUCT_DETAILS = 'GET_STOCK_PRODUCT_DETAILS';
export const GET_STOCK_PRODUCT_DETAILS_RESET = 'GET_STOCK_PRODUCT_DETAILS_RESET';
export const SUPERADMIN_GET_STOCK = 'SUPERADMIN_GET_STOCK';
