export const LIST_STOCKPRODUCT = 'LIST_STOCKPRODUCT';
export const CREATE_STOCKPRODUCT = 'CREATE_STOCKPRODUCT';
export const ADD_STOCKPRODUCT = 'ADD_STOCKPRODUCT';
export const GET_STOCKPRODUCT = 'GET_STOCKPRODUCT';
export const UPDATE_STOCKPRODUCT = 'UPDATE_STOCKPRODUCT';
export const DELETE_STOCKPRODUCT = 'DELETE_STOCKPRODUCT';
export const RESET_STOCKPRODUCT = 'RESET_STOCKPRODUCT';
export const RESET_STOCKPRODUCT_LIST = 'RESET_STOCKPRODUCT_LIST';