export const LIST_STOCKPRODUCTBANNER = 'LIST_STOCKPRODUCTBANNER';
export const CREATE_STOCKPRODUCTBANNER = 'CREATE_STOCKPRODUCTBANNER';
export const ADD_STOCKPRODUCTBANNER = 'ADD_STOCKPRODUCTBANNER';
export const GET_STOCKPRODUCTBANNER = 'GET_STOCKPRODUCTBANNER';
export const UPDATE_STOCKPRODUCTBANNER = 'UPDATE_STOCKPRODUCTBANNER';
export const DELETE_STOCKPRODUCTBANNER = 'DELETE_STOCKPRODUCTBANNER';
export const RESET_STOCKPRODUCT = 'RESET_STOCKPRODUCT';
export const RESET_STOCKPRODUCT_LIST = 'RESET_STOCKPRODUCT_LIST';