export const LIST_SUB_CATEGORY = 'LIST_SUB_CATEGORY';
export const ADD_SUB_CATEGORY = 'ADD_SUB_CATEGORY';
export const UPDATE_SUB_CATEGORY = 'UPDATE_SUB_CATEGORY';
export const DELETE_SUB_CATEGORY = 'DELETE_SUB_CATEGORY';
export const RESET_SUB_CATEGORY_LIST = 'RESET_SUB_CATEGORY_LIST';
export const RESET_SUB_CATEGORY_RESET = 'RESET_SUB_CATEGORY_RESET';