export const SUPERADMIN_LIST_SUPPLIER = 'SUPERADMIN_LIST_SUPPLIER';
export const SUPERADMIN_ADD_SUPPLIER = 'SUPERADMIN_ADD_SUPPLIER';
export const SUPERADMIN_UPDATE_SUPPLIER = 'SUPERADMIN_UPDATE_SUPPLIER';
export const SUPERADMIN_DELETE_SUPPLIER = 'SUPERADMIN_DELETE_SUPPLIER';
export const SUPERADMIN_GET_SUPPLIER = 'SUPERADMIN_GET_SUPPLIER';
export const SUPERADMIN_RESET_SUPPLIER = 'SUPERADMIN_RESET_SUPPLIER';