export const SUPERADMIN_LIST_VISIT = 'SUPERADMIN_LIST_VISIT';
export const SUPERADMIN_ADD_VISIT = 'SUPERADMIN_ADD_VISIT';
export const SUPERADMIN_UPDATE_VISIT = 'SUPERADMIN_UPDATE_VISIT';
export const SUPERADMIN_DELETE_VISIT = 'SUPERADMIN_DELETE_VISIT';
export const SUPERADMIN_GET_VISIT = 'SUPERADMIN_GET_VISIT';
export const SUPERADMIN_RESET_VISIT = 'SUPERADMIN_RESET_VISIT';