export const SUPERADMIN_LIST_WORKER = 'SUPERADMIN_LIST_WORKER';
export const SUPERADMIN_ADD_WORKER = 'SUPERADMIN_ADD_WORKER';
export const SUPERADMIN_UPDATE_WORKER = 'SUPERADMIN_UPDATE_WORKER';
export const SUPERADMIN_DELETE_WORKER = 'SUPERADMIN_DELETE_WORKER';
export const SUPERADMIN_GET_WORKER = 'SUPERADMIN_GET_WORKER';
export const SUPERADMIN_RESET_WORKER = 'SUPERADMIN_RESET_WORKER';