export const EMPLOYEE_UPDATE_PROFILE = 'EMPLOYEE_UPDATE_PROFILE';
export const EMPLOYEE_PROFILE_RESET = 'EMPLOYEE_PROFILE_RESET';
export const EMPLOYEE_CHANGE_PASSWORD_RESET = 'EMPLOYEE_CHANGE_PASSWORD_RESET';
export const EMPLOYEE_UPDATE_PASSWORD = 'EMPLOYEE_UPDATE_PASSWORD';
export const EMPLOYEE_DASHBOARD = 'EMPLOYEE_DASHBOARD';