export const DISTRIBUTOR_CART_LIST = 'DISTRIBUTOR_CART_LIST';
export const DISTRIBUTOR_CART_ADD = 'DISTRIBUTOR_CART_ADD';
export const DISTRIBUTOR_CART_DELETE = 'DISTRIBUTOR_CART_DELETE';
export const DISTRIBUTOR_CART_RESET = 'DISTRIBUTOR_CART_RESET';
export const DISTRIBUTOR_CART_RESET_LIST = 'DISTRIBUTOR_CART_RESET_LIST';