export const LIST_LEAVEAPPLICATION = 'LIST_LEAVEAPPLICATION';
export const CREATE_LEAVEAPPLICATION = 'CREATE_LEAVEAPPLICATION';
export const ADD_LEAVEAPPLICATION = 'ADD_LEAVEAPPLICATION';
export const GET_LEAVEAPPLICATION = 'GET_LEAVEAPPLICATION';
export const RESET_LEAVEAPPLICATION = 'RESET_LEAVEAPPLICATION';
export const UPDATE_LEAVEAPPLICATION = 'UPDATE_LEAVEAPPLICATION';
export const DELETE_LEAVEAPPLICATION = 'DELETE_LEAVEAPPLICATION';