export const DISTRIBUTOR_LIST_MYORDERS = 'DISTRIBUTOR_LIST_MYORDERS';
export const DISTRIBUTOR_ADD_MYORDERS = 'DISTRIBUTOR_ADD_MYORDERS';
export const DISTRIBUTOR_GET_MYORDERS = 'DISTRIBUTOR_GET_MYORDERS';
export const DISTRIBUTOR_CANCEL_MYORDER = 'DISTRIBUTOR_CANCEL_MYORDER';
export const DISTRIBUTOR_RESET_MYORDERS = 'DISTRIBUTOR_RESET_MYORDERS';