export const DISTRIBUTOR_LIST_PAYMENT = 'DISTRIBUTOR_LIST_PAYMENT';
export const DISTRIBUTOR_ADD_PAYMENT = 'DISTRIBUTOR_ADD_PAYMENT';
export const DISTRIBUTOR_RESET_PAYMENT = 'DISTRIBUTOR_RESET_PAYMENT';