export const DISTRIBUTOR_LIST_PRODUCT = 'DISTRIBUTOR_LIST_PRODUCT';
export const DISTRIBUTOR_GET_PRODUCT = 'DISTRIBUTOR_GET_PRODUCT';
export const DISTRIBUTOR_RESET_PRODUCT_LIST = 'DISTRIBUTOR_RESET_PRODUCT_LIST';