export const DISTRIBUTOR_UPDATE_PROFILE = 'DISTRIBUTOR_UPDATE_PROFILE';
export const DISTRIBUTOR_PROFILE_RESET = 'DISTRIBUTOR_PROFILE_RESET';
export const DISTRIBUTOR_CHANGE_PASSWORD_RESET = 'DISTRIBUTOR_CHANGE_PASSWORD_RESET';
export const DISTRIBUTOR_UPDATE_PASSWORD = 'DISTRIBUTOR_UPDATE_PASSWORD';
export const DISTRIBUTOR_DASHBOARD = 'DISTRIBUTOR_DASHBOARD';