export const DISTRIBUTOR_LIST_RETAILER = 'DISTRIBUTOR_LIST_RETAILER';
export const DISTRIBUTOR_ADD_RETAILER = 'DISTRIBUTOR_ADD_RETAILER';
export const DISTRIBUTOR_UPDATE_RETAILER = 'DISTRIBUTOR_UPDATE_RETAILER';
export const DISTRIBUTOR_DELETE_RETAILER = 'DISTRIBUTOR_DELETE_RETAILER';
export const DISTRIBUTOR_GET_RETAILER = 'DISTRIBUTOR_GET_RETAILER';
export const DISTRIBUTOR_RESET_RETAILER = 'DISTRIBUTOR_RESET_RETAILER';