export const DISTRIBUTOR_LIST_SALE_EXECUTIVE = 'DISTRIBUTOR_LIST_SALE_EXECUTIVE';
export const DISTRIBUTOR_ADD_SALE_EXECUTIVE = 'DISTRIBUTOR_ADD_SALE_EXECUTIVE';
export const DISTRIBUTOR_UPDATE_SALE_EXECUTIVE = 'DISTRIBUTOR_UPDATE_SALE_EXECUTIVE';
export const DISTRIBUTOR_DELETE_SALE_EXECUTIVE = 'DISTRIBUTOR_DELETE_SALE_EXECUTIVE';
export const DISTRIBUTOR_GET_SALE_EXECUTIVE = 'DISTRIBUTOR_GET_SALE_EXECUTIVE';
export const DISTRIBUTOR_RESET_SALE_EXECUTIVE = 'DISTRIBUTOR_RESET_SALE_EXECUTIVE';