export const DISTRIBUTOR_LIST_SALES = 'DISTRIBUTOR_LIST_SALES';
export const DISTRIBUTOR_CREATE_SALES = 'DISTRIBUTOR_CREATE_SALES';
export const DISTRIBUTOR_ADD_SALES = 'DISTRIBUTOR_ADD_SALES';
export const DISTRIBUTOR_GET_SALES = 'DISTRIBUTOR_GET_SALES';
export const DISTRIBUTOR_UPDATE_SALES = 'DISTRIBUTOR_UPDATE_SALES';
export const DISTRIBUTOR_DELETE_SALES = 'DISTRIBUTOR_DELETE_SALES';
export const DISTRIBUTOR_RESET_SALES = 'DISTRIBUTOR_RESET_SALES';