export const DISTRIBUTOR_SALE_CART_LIST = 'DISTRIBUTOR_SALE_CART_LIST';
export const DISTRIBUTOR_SALE_CART_ADD = 'DISTRIBUTOR_SALE_CART_ADD';
export const DISTRIBUTOR_SALE_CART_DELETE = 'DISTRIBUTOR_SALE_CART_DELETE';
export const DISTRIBUTOR_SALE_CART_RESET = 'DISTRIBUTOR_SALE_CART_RESET';
export const DISTRIBUTOR_SALE_CART_RESET_LIST = 'DISTRIBUTOR_SALE_CART_RESET_LIST';