export const DISTRIBUTOR_LIST_STOCKAPPLICATION = 'DISTRIBUTOR_LIST_STOCKAPPLICATION';
export const DISTRIBUTOR_ADD_STOCKAPPLICATION = 'DISTRIBUTOR_ADD_STOCKAPPLICATION';
export const DISTRIBUTOR_GET_STOCK_PRODUCT_LIST = 'DISTRIBUTOR_GET_STOCK_PRODUCT_LIST';
export const DISTRIBUTOR_GET_STOCK_PRODUCT_DETAILS = 'DISTRIBUTOR_GET_STOCK_PRODUCT_DETAILS';
export const DISTRIBUTOR_GET_STOCK_PRODUCT_DETAILS_RESET = 'DISTRIBUTOR_GET_STOCK_PRODUCT_DETAILS_RESET';
export const DISTRIBUTOR_GET_STOCK = 'DISTRIBUTOR_GET_STOCK';

