export const SE_UPDATE_PROFILE = 'SE_UPDATE_PROFILE';
export const SE_PROFILE_RESET = 'SE_PROFILE_RESET';
export const SE_CHANGE_PASSWORD_RESET = 'SE_CHANGE_PASSWORD_RESET';
export const SE_UPDATE_PASSWORD = 'SE_UPDATE_PASSWORD';
export const SE_DASHBOARD = 'SE_DASHBOARD';