export const ADMIN_CART_LIST = 'ADMIN_CART_LIST';
export const ADMIN_CART_ADD = 'ADMIN_CART_ADD';
export const ADMIN_CART_DELETE = 'ADMIN_CART_DELETE';
export const ADMIN_CART_RESET = 'ADMIN_CART_RESET';
export const ADMIN_CART_RESET_LIST = 'ADMIN_CART_RESET_LIST';