export const ADMIN_LIST_DISTRIBUTOR = 'ADMIN_LIST_DISTRIBUTOR';
export const ADMIN_ADD_DISTRIBUTOR = 'ADMIN_ADD_DISTRIBUTOR';
export const ADMIN_UPDATE_DISTRIBUTOR = 'ADMIN_UPDATE_DISTRIBUTOR';
export const ADMIN_DELETE_DISTRIBUTOR = 'ADMIN_DELETE_DISTRIBUTOR';
export const ADMIN_GET_DISTRIBUTOR = 'ADMIN_GET_DISTRIBUTOR';
export const ADMIN_RESET_DISTRIBUTOR = 'ADMIN_RESET_DISTRIBUTOR';