export const ADMIN_LIST_ORDERS = 'ADMIN_LIST_ORDERS';
export const ADMIN_ADD_ORDERS = 'ADMIN_ADD_ORDERS';
export const ADMIN_GET_ORDERS = 'ADMIN_GET_ORDERS';
export const ADMIN_CANCEL_ORDER = 'ADMIN_CANCEL_ORDER';
export const ADMIN_RESET_ORDERS = 'ADMIN_RESET_ORDERS';