export const ADMIN_LIST_PAYMENT = 'ADMIN_LIST_PAYMENT';
export const ADMIN_ADD_PAYMENT = 'ADMIN_ADD_PAYMENT';
export const ADMIN_RESET_PAYMENT = 'ADMIN_RESET_PAYMENT';
export const ADMIN_DUE_PAYMENT = 'ADMIN_DUE_PAYMENT';
export const ADMIN_RESET_ALL_PAYMENT = 'ADMIN_RESET_ALL_PAYMENT';
export const ADMIN_LIST_WALLET = 'ADMIN_LIST_WALLET';