export const ADMIN_UPDATE_PROFILE = 'ADMIN_UPDATE_PROFILE';
export const ADMIN_PROFILE_RESET = 'ADMIN_PROFILE_RESET';
export const ADMIN_CHANGE_PASSWORD_RESET = 'ADMIN_CHANGE_PASSWORD_RESET';
export const ADMIN_UPDATE_PASSWORD = 'ADMIN_UPDATE_PASSWORD';
export const ADMIN_DASHBOARD = 'ADMIN_DASHBOARD';