export const ADMIN_SALE_CART_LIST = 'ADMIN_SALE_CART_LIST';
export const ADMIN_SALE_CART_ADD = 'ADMIN_SALE_CART_ADD';
export const ADMIN_SALE_CART_DELETE = 'ADMIN_SALE_CART_DELETE';
export const ADMIN_SALE_CART_RESET = 'ADMIN_SALE_CART_RESET';
export const ADMIN_SALE_CART_RESET_LIST = 'ADMIN_SALE_CART_RESET_LIST';