export const ADMIN_LIST_SALES = 'ADMIN_LIST_SALES';
export const ADMIN_CREATE_SALES = 'ADMIN_CREATE_SALES';
export const ADMIN_ADD_SALES = 'ADMIN_ADD_SALES';
export const ADMIN_GET_SALES = 'ADMIN_GET_SALES';
export const ADMIN_UPDATE_SALES = 'ADMIN_UPDATE_SALES';
export const ADMIN_DELETE_SALES = 'ADMIN_DELETE_SALES';
export const ADMIN_RESET_SALES = 'ADMIN_RESET_SALES';