export const ADMIN_LIST_STOCKAPPLICATION = 'ADMIN_LIST_STOCKAPPLICATION';
export const ADMIN_ADD_STOCKAPPLICATION = 'ADMIN_ADD_STOCKAPPLICATION';
export const ADMIN_GET_STOCK_PRODUCT_LIST = 'ADMIN_GET_STOCK_PRODUCT_LIST';
export const ADMIN_GET_STOCK_PRODUCT_DETAILS = 'ADMIN_GET_STOCK_PRODUCT_DETAILS';
export const ADMIN_GET_STOCK_PRODUCT_DETAILS_RESET = 'ADMIN_GET_STOCK_PRODUCT_DETAILS_RESET';
export const ADMIN_GET_STOCK = 'ADMIN_GET_STOCK';

