export const ADMIN_LIST_SUPPLIER = 'ADMIN_LIST_SUPPLIER';
export const ADMIN_ADD_SUPPLIER = 'ADMIN_ADD_SUPPLIER';
export const ADMIN_UPDATE_SUPPLIER = 'ADMIN_UPDATE_SUPPLIER';
export const ADMIN_DELETE_SUPPLIER = 'ADMIN_DELETE_SUPPLIER';
export const ADMIN_GET_SUPPLIER = 'ADMIN_GET_SUPPLIER';
export const ADMIN_RESET_SUPPLIER = 'ADMIN_RESET_SUPPLIER';