export const DESTROY_SESSION = 'DESTROY_SESSION';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const UPDATE_GLOBAL_AUTH = 'UPDATE_GLOBAL_AUTH';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';