export const LIST_STOCK_HISTORY = 'LIST_STOCK_HISTORY';
export const ADD_STOCK_HISTORY = 'ADD_STOCK_HISTORY';
export const UPDATE_STOCK_HISTORY = 'UPDATE_STOCK_HISTORY';
export const DELETE_STOCK_HISTORY = 'DELETE_STOCK_HISTORY';
export const GET_STOCK_HISTORY = 'GET_STOCK_HISTORY';
export const RESET_STOCK_HISTORY = 'RESET_STOCK_HISTORY';
export const GET_STOCK_HISTORY_MATERIALS = 'GET_STOCK_HISTORY_MATERIALS';
export const RESET_STOCK_HISTORY_MATERIALS = 'RESET_STOCK_HISTORY_MATERIALS';